import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from "../data/products.json";
import Products from '../components/Products'
import Navbar from '../components/Navbar'
import React, { useReducer } from 'react'
import { Provider, useSelector } from 'react-redux'
import { store } from '../features/store'


export default function Home() {

  // const productsList = useSelector((state) => state.products)
  // const products = productsList.list;
  // console.log("Products: ", productsList)
  
  return (
        <div className="container">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Navbar />
          <Products products={products} />
        </div>
  )
}
